
<!doctype html>
<html ng-app="MyApp">
<head>
    <meta charset="UTF-8" />
    <title>Zend com Angular</title>
    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="wrap">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Zend 2 + Angular</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#/categorias">Categorias</a></li>
                    <li><a href="#/produtos">Produtos</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <?php echo $this->content; ?>
    <div class="footer">
        <div class="container">
            <p class="text-muted credit">
                Code64.com.br
            </p>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-route.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-resource.min.js"></script>
<script src="/projeto-angular/app.js"></script>
<script src="/projeto-angular/controllers.js"></script>
<script src="/projeto-angular/services.js"></script>
</body>
</html>